/**
 * Battle DTOs for Fantasy Autobattler API.
 * Swagger documentation for battle-related endpoints and responses with validation.
 * 
 * @fileoverview DTO classes for battle data with comprehensive API documentation and validation.
 */

import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsString, IsEnum } from 'class-validator';

/**
 * Core 2.0 Mechanic Event Types.
 * All event types generated by the modular mechanics system.
 */
export enum MechanicEventType {
  /** Facing: Unit changes facing direction (Tier 0) */
  FACING = 'mechanic_facing',
  
  /** Resolve: Morale damage, regeneration, or break (Tier 1) */
  RESOLVE = 'mechanic_resolve',
  
  /** Routing: Unit retreats or crumbles due to zero resolve (Tier 1) */
  ROUTING = 'mechanic_routing',
  
  /** Engagement: Zone of Control applied (Tier 1) */
  ENGAGEMENT = 'mechanic_engagement',
  
  /** Attack of Opportunity: Free attack when enemy leaves ZoC (Tier 1) */
  ATTACK_OF_OPPORTUNITY = 'mechanic_aoo',
  
  /** Flanking: Damage modifier from attack arc (front/flank/rear) (Tier 1) */
  FLANKING = 'mechanic_flanking',
  
  /** Riposte: Counter-attack after being attacked (Tier 2) */
  RIPOSTE = 'mechanic_riposte',
  
  /** Intercept: Hard intercept (stop cavalry) or soft intercept (engage) (Tier 2) */
  INTERCEPT = 'mechanic_intercept',
  
  /** Aura: Area effect applied to nearby units (Tier 2) */
  AURA = 'mechanic_aura',
  
  /** Charge: Cavalry momentum bonus from movement (Tier 3) */
  CHARGE = 'mechanic_charge',
  
  /** Overwatch: Ranged reaction shot during enemy movement (Tier 3) */
  OVERWATCH = 'mechanic_overwatch',
  
  /** Phalanx: Formation bonuses from adjacent allies (Tier 3) */
  PHALANX = 'mechanic_phalanx',
  
  /** Line of Sight: Direct fire blocked or arc fire penalty (Tier 3) */
  LINE_OF_SIGHT = 'mechanic_los',
  
  /** Ammunition: Ammo consumed or reloaded (Tier 3) */
  AMMUNITION = 'mechanic_ammo',
  
  /** Contagion: Status effect spreads to adjacent units (Tier 4) */
  CONTAGION = 'mechanic_contagion',
  
  /** Armor Shred: Armor reduction from physical attacks (Tier 4) */
  ARMOR_SHRED = 'mechanic_armor_shred',
}

/**
 * Mechanic event metadata examples for Swagger documentation.
 */
export const MECHANIC_EVENT_EXAMPLES = {
  [MechanicEventType.FACING]: {
    type: 'mechanic_facing',
    actorId: 'knight-1',
    targetId: 'knight-1',
    previousFacing: 'N',
    newFacing: 'E',
    reason: 'attack',
    round: 1,
    metadata: {
      description: 'Unit turned to face target before attacking'
    }
  },
  [MechanicEventType.RESOLVE]: {
    type: 'mechanic_resolve',
    actorId: 'knight-1',
    targetId: 'knight-1',
    changeType: 'regen',
    amount: 5,
    newResolve: 85,
    round: 1,
    metadata: {
      description: 'Unit regenerated resolve at turn start'
    }
  },
  [MechanicEventType.FLANKING]: {
    type: 'mechanic_flanking',
    actorId: 'rogue-1',
    targetId: 'knight-1',
    arc: 'rear',
    damageModifier: 1.5,
    resolveDamage: 20,
    riposteDisabled: true,
    round: 2,
    metadata: {
      description: 'Rogue attacked from rear, dealing +50% damage and 20 resolve damage'
    }
  },
  [MechanicEventType.RIPOSTE]: {
    type: 'mechanic_riposte',
    actorId: 'duelist-1',
    targetId: 'berserker-1',
    damage: 15,
    chargesRemaining: 2,
    round: 3,
    metadata: {
      description: 'Duelist counter-attacked after being hit'
    }
  },
  [MechanicEventType.INTERCEPT]: {
    type: 'mechanic_intercept',
    actorId: 'spearman-1',
    targetId: 'cavalry-1',
    interceptType: 'hard',
    damage: 20,
    position: { x: 3, y: 4 },
    stoppedAt: { x: 3, y: 4 },
    round: 4,
    metadata: {
      description: 'Spearman stopped charging cavalry with hard intercept'
    }
  },
  [MechanicEventType.CHARGE]: {
    type: 'mechanic_charge',
    actorId: 'cavalry-1',
    targetId: 'archer-1',
    chargeDistance: 4,
    momentum: 0.8,
    damageBonus: 16,
    countered: false,
    round: 5,
    metadata: {
      description: 'Cavalry charged 4 cells, gaining 80% momentum bonus'
    }
  },
  [MechanicEventType.PHALANX]: {
    type: 'mechanic_phalanx',
    actorId: 'hoplite-1',
    targetId: 'hoplite-1',
    action: 'formed',
    adjacentAllies: 3,
    armorBonus: 3,
    resolveBonus: 15,
    round: 1,
    metadata: {
      description: 'Hoplite formed phalanx with 3 adjacent allies'
    }
  },
  [MechanicEventType.OVERWATCH]: {
    type: 'mechanic_overwatch',
    actorId: 'crossbowman-1',
    targetId: 'cavalry-1',
    hit: true,
    damage: 18,
    shotsRemaining: 1,
    round: 6,
    metadata: {
      description: 'Crossbowman fired overwatch shot at moving cavalry'
    }
  },
  [MechanicEventType.CONTAGION]: {
    type: 'mechanic_contagion',
    actorId: 'plaguebearer-1',
    sourceId: 'plaguebearer-1',
    targetId: 'knight-1',
    effectType: 'plague',
    success: true,
    spreadChance: 0.6,
    phalanxBonus: false,
    round: 7,
    metadata: {
      description: 'Plague spread from plaguebearer to adjacent knight'
    }
  },
  [MechanicEventType.ARMOR_SHRED]: {
    type: 'mechanic_armor_shred',
    actorId: 'berserker-1',
    targetId: 'knight-1',
    shredApplied: 1,
    totalShred: 3,
    baseArmor: 10,
    effectiveArmor: 7,
    wasCapped: false,
    round: 8,
    metadata: {
      description: 'Berserker shredded 1 armor, total shred now 3'
    }
  },
  [MechanicEventType.ATTACK_OF_OPPORTUNITY]: {
    type: 'mechanic_aoo',
    actorId: 'guardian-1',
    targetId: 'rogue-1',
    damage: 12,
    hit: true,
    fromPosition: { x: 2, y: 3 },
    toPosition: { x: 3, y: 3 },
    round: 9,
    metadata: {
      description: 'Guardian got free attack as rogue left Zone of Control'
    }
  },
};

/**
 * Mechanic event DTO for Core 2.0 mechanic events.
 * Provides detailed documentation for all mechanic event types.
 */
export class MechanicEventDto {
  @ApiProperty({
    description: 'Mechanic event type',
    enum: MechanicEventType,
    example: MechanicEventType.FLANKING,
  })
  type!: MechanicEventType;

  @ApiProperty({
    description: 'Battle round number (1-based)',
    example: 2,
    minimum: 1,
  })
  round!: number;

  @ApiProperty({
    description: 'ID of the acting unit',
    example: 'rogue-1',
  })
  actorId!: string;

  @ApiProperty({
    description: 'ID of the target unit (if applicable)',
    example: 'knight-1',
    required: false,
  })
  targetId?: string;

  @ApiProperty({
    description: 'Additional event metadata (varies by mechanic type)',
    example: {
      arc: 'rear',
      damageModifier: 1.5,
      resolveDamage: 20,
      riposteDisabled: true
    },
    type: 'object',
    required: false,
  })
  metadata?: Record<string, unknown>;
}

/**
 * Battle result DTO for battle simulation responses.
 */
export class BattleResultDto {
  @ApiProperty({
    description: 'Unique battle identifier',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  id!: string;

  @ApiProperty({
    description: 'Battle winner (player or bot)',
    example: 'player',
    enum: ['player', 'bot', 'draw'],
  })
  winner!: string;

  @ApiProperty({
    description: 'Number of rounds the battle lasted',
    example: 15,
    minimum: 1,
    maximum: 100,
  })
  rounds!: number;

  @ApiProperty({
    description: 'Battle events for replay (includes Core 1.0 events and Core 2.0 mechanic events)',
    example: [
      {
        type: 'move',
        unitId: 'knight-1',
        from: { x: 0, y: 0 },
        to: { x: 1, y: 0 },
        round: 1
      },
      {
        type: 'mechanic_flanking',
        actorId: 'rogue-1',
        targetId: 'knight-1',
        arc: 'rear',
        damageModifier: 1.5,
        resolveDamage: 20,
        round: 2
      }
    ],
    type: 'array',
    items: { type: 'object' },
  })
  events!: object[];

  @ApiProperty({
    description: 'Mechanic events generated by Core 2.0 mechanics (subset of events array)',
    example: [
      {
        type: 'mechanic_facing',
        actorId: 'knight-1',
        targetId: 'knight-1',
        previousFacing: 'N',
        newFacing: 'E',
        reason: 'attack',
        round: 1
      },
      {
        type: 'mechanic_flanking',
        actorId: 'rogue-1',
        targetId: 'knight-1',
        arc: 'rear',
        damageModifier: 1.5,
        resolveDamage: 20,
        riposteDisabled: true,
        round: 2
      }
    ],
    type: 'array',
    items: { type: 'object' },
    required: false,
  })
  mechanicEvents?: object[];

  @ApiProperty({
    description: 'Mechanics preset used for battle simulation (Core 2.0)',
    example: 'mvp',
    enum: ['mvp', 'tactical', 'roguelike', 'custom'],
    required: false,
  })
  mechanicsPreset?: 'mvp' | 'tactical' | 'roguelike' | 'custom';

  @ApiProperty({
    description: 'Count of mechanic events by type (for analytics)',
    example: {
      mechanic_facing: 15,
      mechanic_flanking: 8,
      mechanic_resolve: 12,
      mechanic_riposte: 3
    },
    type: 'object',
    required: false,
  })
  mechanicEventCounts?: Record<string, number>;

  @ApiProperty({
    description: 'Player team composition',
    example: ['knight', 'mage', 'priest'],
    type: [String],
  })
  playerTeam!: string[];

  @ApiProperty({
    description: 'Bot team composition',
    example: ['berserker', 'archer', 'warlock'],
    type: [String],
  })
  botTeam!: string[];

  @ApiProperty({
    description: 'Battle creation timestamp',
    example: '2025-12-11T14:30:00.000Z',
  })
  createdAt!: string;
}

/**
 * Battle log DTO for battle history responses.
 */
export class BattleLogDto {
  @ApiProperty({
    description: 'Unique battle identifier',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  id!: string;

  @ApiProperty({
    description: 'Player 1 identifier',
    example: '456e7890-e89b-12d3-a456-426614174001',
  })
  player1Id!: string;

  @ApiProperty({
    description: 'Player 2 identifier (or bot)',
    example: 'bot',
  })
  player2Id!: string;

  @ApiProperty({
    description: 'Battle winner identifier',
    example: '456e7890-e89b-12d3-a456-426614174001',
  })
  winnerId!: string;

  @ApiProperty({
    description: 'Player 1 team snapshot',
    example: {
      units: ['knight', 'mage', 'priest'],
      positions: [{ x: 0, y: 0 }, { x: 1, y: 0 }, { x: 2, y: 0 }]
    },
    type: 'object',
  })
  player1Team!: object;

  @ApiProperty({
    description: 'Player 2 team snapshot',
    example: {
      units: ['berserker', 'archer', 'warlock'],
      positions: [{ x: 0, y: 8 }, { x: 1, y: 8 }, { x: 2, y: 8 }]
    },
    type: 'object',
  })
  player2Team!: object;

  @ApiProperty({
    description: 'Complete battle events for replay',
    type: 'array',
    items: { type: 'object' },
  })
  events!: object[];

  @ApiProperty({
    description: 'Random seed used for battle simulation',
    example: 1234567890,
  })
  seed!: number;

  @ApiProperty({
    description: 'Battle status',
    example: 'completed',
    enum: ['pending', 'in_progress', 'completed', 'cancelled'],
  })
  status!: string;

  @ApiProperty({
    description: 'Battle creation timestamp',
    example: '2025-12-11T14:30:00.000Z',
  })
  createdAt!: string;

  @ApiProperty({
    description: 'Battle completion timestamp',
    example: '2025-12-11T14:35:00.000Z',
  })
  updatedAt!: string;
}

/**
 * Battle list response DTO.
 */
export class BattleListResponseDto {
  @ApiProperty({
    description: 'Array of battle logs',
    type: [BattleLogDto],
  })
  battles!: BattleLogDto[];

  @ApiProperty({
    description: 'Total number of battles',
    example: 25,
  })
  total!: number;
}

/**
 * Path parameter DTO for battle ID.
 */
export class BattleIdParamDto {
  @ApiProperty({
    description: 'Battle identifier',
    example: '123e4567-e89b-12d3-a456-426614174000',
  })
  id!: string;
}
/**
 * DTO for starting a battle.
 * Used in POST /battle/start endpoint.
 */
export class StartBattleDto {
  @ApiProperty({
    description: 'Battle difficulty level',
    example: 'medium',
    enum: ['easy', 'medium', 'hard'],
    required: false,
  })
  @IsOptional()
  @IsString({ message: 'Difficulty must be a string' })
  @IsEnum(['easy', 'medium', 'hard'], { message: 'Difficulty must be easy, medium, or hard' })
  difficulty?: string;

  @ApiProperty({
    description: 'Optional team ID to use (defaults to active team)',
    example: '123e4567-e89b-12d3-a456-426614174000',
    required: false,
  })
  @IsOptional()
  @IsString({ message: 'Team ID must be a string' })
  teamId?: string;

  @ApiProperty({
    description: 'Mechanics preset for battle simulation (Core 2.0)',
    example: 'mvp',
    enum: ['mvp', 'tactical', 'roguelike', 'custom'],
    required: false,
  })
  @IsOptional()
  @IsString({ message: 'Mechanics preset must be a string' })
  @IsEnum(['mvp', 'tactical', 'roguelike', 'custom'], { 
    message: 'Mechanics preset must be mvp, tactical, roguelike, or custom' 
  })
  mechanicsPreset?: 'mvp' | 'tactical' | 'roguelike' | 'custom';

  @ApiProperty({
    description: 'Custom mechanics toggles (used when mechanicsPreset is "custom")',
    example: { facing: true, flanking: true, riposte: false },
    required: false,
    type: 'object',
  })
  @IsOptional()
  mechanicsToggles?: Record<string, boolean>;
}